
def func():
    raise Exception()

try:
    func()
except Exception:
    print
